#!/bin/bash

echo "Deleting Round 3: 81 obsolete files..."
echo ""

# Category 1: Duplicate analysis (30 files)
rm -fv ./ARCHITECTURE_ANALYSIS.md
rm -fv ./CLLM_AI_SYSTEM_ANALYSIS.md
rm -fv ./CLLM_ALGORITHM_ANALYSIS.md
rm -fv ./CODE_CLEANUP_ANALYSIS.md
rm -fv ./COMPREHENSIVE_ANALYSIS.md
rm -fv ./COMPREHENSIVE_LIBRARY_ANALYSIS.md
rm -fv ./DEEP_ANALYSIS_PLAN.md
rm -fv ./DEEP_ANALYSIS_REPORT.md
rm -fv ./DEEP_SCHEMA_ANALYSIS.md
rm -fv ./DEEP_SYSTEM_AUDIT.md
rm -fv ./DETAILED_API_ANALYSIS.md
rm -fv ./LATTICE_INTEGRATION_ANALYSIS.md
rm -fv ./LIBRARY_ANALYSIS.md
rm -fv ./LIBRARY_ANALYSIS_EXECUTIVE_SUMMARY.md
rm -fv ./LIBRARY_DEPENDENCY_GRAPH.md
rm -fv ./LIBRARY_INVENTORY.md
rm -fv ./MASTER_PLAN_DEEP_ANALYSIS.md
rm -fv ./MATHEMATICAL_INTEGRITY_ANALYSIS.md
rm -fv ./MEMORY_ACCESS_ANALYSIS.md
rm -fv ./OBJECTIVE_11_ANALYSIS.md
rm -fv ./OBJECTIVE_15_UI_CLI_ANALYSIS.md
rm -fv ./OBJECTIVE_2_ANALYSIS.md
rm -fv ./PERFORMANCE_ANALYSIS_SUMMARY.md
rm -fv ./PERFORMANCE_ISSUE_ANALYSIS.md
rm -fv ./PIPELINE_ANALYSIS.md
rm -fv ./PIPELINE_DEEP_ANALYSIS.md
rm -fv ./REDUNDANCY_ANALYSIS.md
rm -fv ./SPHERE_IMPLEMENTATIONS_COMPARISON.md
rm -fv ./SYSTEM_ANALYSIS.md
rm -fv ./THREADING_ARCHITECTURE_ANALYSIS.md

# Category 2: Historical reports (20 files)
rm -fv ./ALL_TESTS_PASSING.md
rm -fv ./BUG_FIX_REPORT.md
rm -fv ./BUILD_VALIDATION_REPORT.md
rm -fv ./BUILD_WARNINGS_FIXED.md
rm -fv ./COMMIT_VERIFICATION_REPORT.md
rm -fv ./CONDITIONAL_COMPILATION_REPORT.md
rm -fv ./CRITICAL_FIXES_APPLIED.md
rm -fv ./CRITICAL_FIX_MATH_LIBRARY.md
rm -fv ./DAY1_SYSTEM_VERIFICATION.md
rm -fv ./DAY2_SPHERE_STATS_API.md
rm -fv ./DAY3_SPHERE_VISUALIZATION.md
rm -fv ./DAY4_SUCCESS_REPORT.md
rm -fv ./DAY4_TRAINING_GUIDE.md
rm -fv ./DAY4_TRAINING_INFERENCE_REPORT.md
rm -fv ./FIXES_APPLIED.md
rm -fv ./MATH_LIBRARY_INDEPENDENCE_VERIFIED.md
rm -fv ./OBJECTIVE_16_TECHNICAL_DEBT_REPORT.md
rm -fv ./PROJECT_COMPLETION_REPORT.md
rm -fv ./TRAINING_SYSTEM_FIXED.md
rm -fv ./WARNING_FIXES_PHASE1_PHASE2.md

# Category 3: Duplicate implementations (15 files)
rm -fv ./ATTENTION_BACKWARD_IMPLEMENTATION.md
rm -fv ./IMPLEMENTATION_REPORT.md
rm -fv ./INTEGRATION_TEST_RESULTS.md
rm -fv ./KISSING_SPHERES_ACTIVATED.md
rm -fv ./PERFORMANCE_FIX_APPLIED.md
rm -fv ./PERFORMANCE_FIX_RESULTS.md
rm -fv ./PHASE2_ATTENTION_BACKWARD.md
rm -fv ./PHASE2_TRAINING_TESTING_REPORT.md
rm -fv ./RECURSIVE_SPHERES_IMPLEMENTATION.md
rm -fv ./RECURSIVE_SPHERE_ARCHITECTURE.md
rm -fv ./RECURSIVE_SPHERE_IMPLEMENTATION.md
rm -fv ./TRAINING_EXECUTION_INSTRUCTIONS.md
rm -fv ./TRAINING_OPTIMIZATION_FIX.md
rm -fv ./TRAINING_SYSTEM_EVALUATION.md
rm -fv ./VALIDATION_TEST_RESULTS.md

# Category 4: Miscellaneous obsolete (16 files)
rm -fv ./BUILD_EXPLANATION.md
rm -fv ./CHANGES_SUMMARY.md
rm -fv ./CLLM_REASSESSMENT.md
rm -fv ./COMPREHENSIVE_TEST_REPORT.md
rm -fv ./CRITICAL_ANALYSIS.md
rm -fv ./CRITICAL_BUG_FOUND_VOCABULARY_LOOP.md
rm -fv ./CRITICAL_FINDINGS.md
rm -fv ./CRITICAL_OPTIMIZER_ISSUE.md
rm -fv ./EXECUTIVE_SUMMARY.md
rm -fv ./FILES_TO_DELETE.md
rm -fv ./FIXES_NEEDED.md
rm -fv ./GITHUB_PUSH_INSTRUCTIONS.md
rm -fv ./GIT_COMMIT_INSTRUCTIONS.md
rm -fv ./HONEST_ASSESSMENT.md
rm -fv ./IMMEDIATE_OPTIMIZATIONS.md
rm -fv ./OPTIMIZATION_RECOMMENDATIONS.md

echo ""
echo "Done! Checking remaining files..."
echo "Total MD files now: $(find . -name '*.md' -type f | grep -v repo_training_data | wc -l)"