#!/bin/bash

echo "Deleting Round 2: 103 obsolete files..."
echo ""

# Category 1: FINAL documents (17 files)
rm -fv ./FINAL_ANALYSIS_AND_PLAN.md
rm -fv ./FINAL_ANALYSIS_REPORT.md
rm -fv ./FINAL_ANALYSIS_SUMMARY.md
rm -fv ./FINAL_COMPREHENSIVE_ANALYSIS.md
rm -fv ./FINAL_COMPREHENSIVE_SUMMARY.md
rm -fv ./FINAL_CORRECTION_SUMMARY.md
rm -fv ./FINAL_DIAGNOSIS.md
rm -fv ./FINAL_IMPLEMENTATION_REPORT.md
rm -fv ./FINAL_REEVALUATION_REPORT.md
rm -fv ./FINAL_REPORT.md
rm -fv ./FINAL_SUMMARY.md
rm -fv ./FINAL_TRAINING_SYSTEM_REPORT.md
rm -fv ./PHASE1_DAY1_FINAL_SUMMARY.md
rm -fv ./PHASE3_FINAL_SUMMARY.md
rm -fv ./RECURSIVE_SPHERES_FINAL_SUMMARY.md
rm -fv ./THREADING_FINAL_APPROACH.md
rm -fv ./SESSION_PROGRESS_SUMMARY.md

# Category 2: COMPLETE reports (48 files)
rm -fv ./ANALYSIS_COMPLETE_SUMMARY.md
rm -fv ./ARCHITECTURAL_REDESIGN_COMPLETE.md
rm -fv ./CLEANUP_COMPLETE.md
rm -fv ./COMPLETE_ANALYSIS_SUMMARY.md
rm -fv ./COMPLETE_FIX_SUMMARY.md
rm -fv ./COMPLETE_IMPLEMENTATION_SUMMARY.md
rm -fv ./COMPLETE_MATHEMATICAL_PURITY_ACHIEVED.md
rm -fv ./COMPLETE_PROJECT_ROADMAP.md
rm -fv ./COMPLETE_SYSTEM_FIX.md
rm -fv ./CRYSTALLINE_PHASE1_COMPLETE.md
rm -fv ./DAY12_COMPLETE_PIPELINE.md
rm -fv ./DAY12_INTEGRATION_COMPLETE.md
rm -fv ./DAY16_HIERARCHICAL_PRIMES_COMPLETE.md
rm -fv ./DAY17_HIERARCHICAL_STRUCTURES_COMPLETE.md
rm -fv ./DAY18_BATCH_PROCESSING_COMPLETE.md
rm -fv ./DYNAMIC_THREADING_COMPLETE.md
rm -fv ./FULL_ATTENTION_BACKWARD_COMPLETE.md
rm -fv ./IMPLEMENTATION_COMPLETE.md
rm -fv ./IMPLEMENTATION_COMPLETE_SUMMARY.md
rm -fv ./IMPROVEMENTS_COMPLETE.md
rm -fv ./KISSING_SPHERES_COMPLETE_ANALYSIS.md
rm -fv ./KISSING_SPHERES_THREADING_COMPLETE.md
rm -fv ./OBJECTIVE_10_COMPLETE.md
rm -fv ./OBJECTIVE_16_PHASE2_COMPLETE.md
rm -fv ./OBJECTIVE_5_COMPLETE.md
rm -fv ./OBJECTIVE_6A_COMPLETE.md
rm -fv ./OBJECTIVE_7A_PHASE1_COMPLETE.md
rm -fv ./OBJECTIVE_9_COMPLETE.md
rm -fv ./OBJECTIVES_2_12_COMPLETE.md
rm -fv ./PHASE1_BUILD_VALIDATION_COMPLETE.md
rm -fv ./PHASE1_COMPLETE.md
rm -fv ./PHASE1_DAY1_COMPLETE.md
rm -fv ./PHASE1_DAY2_COMPLETE.md
rm -fv ./PHASE1_DAY3_COMPLETE.md
rm -fv ./PHASE1_DAY6_COMPLETE.md
rm -fv ./PHASE2_DAY8_COMPLETE.md
rm -fv ./PHASE2_DAY8_FIXES_COMPLETE.md
rm -fv ./PHASE2_DAYS7-11_COMPLETE.md
rm -fv ./PHASE2_RACE_CONDITION_FIX_COMPLETE.md
rm -fv ./PHASE3_TRAINING_BUG_FIXED.md
rm -fv ./PHASE4_INFERENCE_VALIDATION_COMPLETE.md
rm -fv ./RECURSIVE_SPHERES_COMPLETE.md
rm -fv ./RULE7_COMPLETE.md
rm -fv ./THREADING_FIX_COMPLETE.md
rm -fv ./TRAINING_COMPLETE_REPORT.md
rm -fv ./WORKSPACE_SYSTEM_COMPLETE.md
rm -fv ./PHASE3_TRAINING_CRITICAL_BUG_FOUND.md
rm -fv ./CRITICAL_MILESTONE_ACHIEVED.md
rm -fv ./PHASE4_COMPLETION_REPORT.md

# Category 3: Duplicate plans (18 files) - Keep only MASTER_PLAN.md
rm -fv ./ARCHITECTURAL_REORGANIZATION_PLAN.md
rm -fv ./CLEANUP_AND_INTEGRATION_PLAN.md
rm -fv ./COMPREHENSIVE_ACTION_PLAN.md
rm -fv ./COMPREHENSIVE_FIX_PLAN.md
rm -fv ./CRYSTALLINE_IMPLEMENTATION_PLAN.md
rm -fv ./IMMEDIATE_ACTION_PLAN.md
rm -fv ./IMPLEMENTATION_ACTION_PLAN.md
rm -fv ./IMPLEMENTATION_PLAN.md
rm -fv ./IMPLEMENTATION_ROADMAP.md
rm -fv ./MASTER_PLAN_IMPROVEMENT_PROPOSALS.md
rm -fv ./MASTER_PLAN_REVISED_PROPOSALS.md
rm -fv ./PHASE2_IMPLEMENTATION_PLAN.md
rm -fv ./PRIORITY_IMPROVEMENTS_PLAN.md
rm -fv ./PRODUCTION_READINESS_PLAN.md
rm -fv ./PURE_CRYSTALLINE_IMPLEMENTATION_PLAN.md
rm -fv ./SHARED_MEMORY_INTEGRATION_PLAN.md
rm -fv ./TESTING_PLAN.md
rm -fv ./THREADING_FIX_PLAN.md

# Category 4: Duplicate summaries (15 files)
rm -fv ./DAY12_INTEGRATION_SUMMARY.md
rm -fv ./DAY12_SUMMARY.md
rm -fv ./LIBALGORITHMS_CREATION_SUMMARY.md
rm -fv ./OBJECTIVE_14_PHASE3_SUMMARY.md
rm -fv ./PHASE2_SUMMARY.md
rm -fv ./PROJECT_COMPLETION_SUMMARY.md
rm -fv ./SUMMARY_FOR_USER.md
rm -fv ./TEST_EXECUTION_SUMMARY.md
rm -fv ./TEST_RESULTS_SUMMARY.md
rm -fv ./TEST_SUMMARY.md
rm -fv ./TRAINING_INFERENCE_SUMMARY.md
rm -fv ./BUILD_WARNING_FIXES_SUMMARY.md
rm -fv ./CODE_CLEANUP_SUMMARY.md
rm -fv ./BLOCKERS_RESOLVED_SUMMARY.md
rm -fv ./COMPREHENSIVE_SYSTEM_ANALYSIS.md

# Category 5: Recent status documents (5 files)
rm -fv ./OPTIMIZED_TRAINING_STATUS.md
rm -fv ./TRAINING_VALIDATION_SUCCESS.md
rm -fv ./TRAINING_PERFORMANCE_BOTTLENECK.md
rm -fv ./CRITICAL_ARCHITECTURE_VIOLATION.md
rm -fv ./RACE_CONDITION_FOUND.md

echo ""
echo "Done! Checking remaining files..."
echo "Total MD files now: $(find . -name '*.md' -type f | grep -v repo_training_data | wc -l)"